name: Parkour
main: nz.co.lolnet.arns.parkour.main
version: ${project.version}
authors: [Arns, James Anderson]
commands:
  Parkour:
    description: Main command!
    usage: /parkour
  Parkour Help:
    description: Parkour help!
    usage: /parkour help
    
permissions: