name: Parkour
main: nz.co.lolnet.arns.parkour.Main
version: 0.1
authors: [Arns, James Anderson]
commands:
  Parkour:
    description: Main command!
    usage: /parkour
  Parkour Help:
    description: Parkour help!
    usage: /parkour help
    
permissions: